const csv = require('csv-parser');
const fs = require('fs');


module.exports = 
{
    getGmmData: function()
    {
        var dataAsList = [];
        fs.createReadStream('./resource/gmm_data.csv')
        .pipe(csv())
        .on('data', (row) => {
          console.log(row);
          dataAsList.push(row['-1.60564'])
        })
        .on('end', () => {
          console.log('CSV file successfully processed ' + dataAsList);
          return dataAsList;
        });        
    },

    getSurveyDataHalf: function () {
      return [true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true];
    },

    getSurveyDataOneThird: function(){
      return [true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true];
    },

    getSurveyDataTwoThird: function(){
      return [true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true];
    }
};
